services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - pgdata:/var/lib/postgresql/data

  app:
    image: ruby
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - rubygems:/usr/local/gem/cache
    ports: 
      - '3000:3000'
    command: sh -c 'bundle && ruby server.rb'

  redis:
    image: redis
    
volumes:
  rubygems:
  pgdata: