#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -v /rubygems:/usr/local/bundle \
  -v /rubygems:/usr/local/gem/cache \
  -p 3000:3000 \
  --network rebase-labs \
  ruby \
  bash -c "bundle && ruby server.rb"